
services:
  api:
    build: .\services\api\
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      MODEL_QUEUE: inference_queue
      DATA_QUEUE: data_queue
    depends_on:
      - rabbitmq
  inference:
    build: .\services\inference\
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      MODEL_QUEUE: inference_queue
    depends_on:
      - rabbitmq
  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: appdb
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
